# Generated by Django 2.2.6 on 2019-10-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstaCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEsta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estado civil',
            },
        ),
    ]
